%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2


imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"




output_path: "/home/uav/fast_drone_ws/vins_output"


cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# o1 521 202509091109
# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 6.4279105628823885e-03, 2.8483922966980213e-02,
#        9.9957358313343136e-01, 6.1725138938169596e-02,
#        -9.9996693791345304e-01, 5.1616419926567847e-03,
#        6.2833535577807575e-03, 2.3035177721808880e-02,
#        -4.9804664227379725e-03, -9.9958092397982001e-01,
#        2.8516159802140173e-02, 9.6693340678445872e-02, 0., 0., 0., 1. ]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 6.4388833565420800e-03, 2.9174189716312082e-02,
#        9.9955360408310168e-01, 5.8414160384624908e-02,
#        -9.9996729650638039e-01, 5.0794056299215962e-03,
#        6.2932945400546170e-03, -2.6697169085558716e-02,
#        -4.8935364351361810e-03, -9.9956143697765953e-01,
#        2.9205941318756312e-02, 9.6919141326693145e-02, 0., 0., 0., 1. ]

# new offline_param
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.03379381, 0.05601212, 
            0.99785802, 0.00128844, 
            -0.99896458, 0.03232157, 
            0.03201699, -0.00405034, 
            -0.030459, -0.99790679, 
            0.0570464, 0.00908112, 0., 0., 0., 1.]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.02889302, 0.05381805, 
            0.99813266, 0.00404231, 
            -0.99914426, 0.03112077, 
            0.02724431, -0.05578878, 
            -0.02959642, -0.99806569, 
            0.05467117, 0.00558867, 0., 0., 0., 1.]
            
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.05                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/fast/savedfiles/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

